---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: mysql-slave-pv-claim
  labels:
    app: mysql-slave
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: default
  name: mysql-slave
  labels:
    name: mysql-slave
spec:
  replicas: 1
  selector:
    name: mysql-slave
  template:
    metadata:
      labels:
        name: mysql-slave
    spec:
      containers:
        - name: slave
          image: paulliu/mysql-slave:0.1
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "test"
            - name: MYSQL_REPLICATION_USER
              value: 'demo'
            - name: MYSQL_REPLICATION_PASSWORD
              value: 'demo'
          volumeMounts:
            - name: mysql-slave-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
      - name: mysql-slave-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-slave-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  labels:
    name: mysql-slave
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
      name: mysql-slave

